spring:
  application:
    name: BenchmarkPostgresJpa
  datasource:
    url: jdbc:postgresql://10.0.0.64:5432/benchmark
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgrespassword
  sql:
    init:
      platform: postgres