spring:
  datasource:
    url: jdbc:postgresql://10.0.0.64:5432/benchmark
    username: postgres
    password: postgrespassword
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres  